services:
  web:
    container_name: proyecto-server-web
    build: 
      context: ./server-web
      dockerfile: Dockerfile
    ports:
      - "${PUERTO_HTTP:-8080}:80"
      - "${PUERTO_HTTPS:-8443}:443"
    volumes:
      - ./pagina_web:/usr/share/nginx/pagina_web
    depends_on:
      - ldap
    restart: unless-stopped

  ftp:
    container_name: proyecto-server-ftp
    build: 
      context: ./server-ftp
      dockerfile: Dockerfile
    ports:
      - "${PUERTO_FTP:-21}:21"
    volumes:
      - ./server-ftp/ftp-users:/home/users
    depends_on:
      - ldap
    restart: unless-stopped

  postgres:
    container_name: proyecto-server-db
    image: postgres:17.4-alpine3.21
    ports:
      - "${PUERTO_DB:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  ldap:
    image: osixia/openldap:1.5.0
    container_name: proyecto-server-ldap
    environment:
      LDAP_ORGANISATION: ${LDAP_ORG}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASS}
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - "${PUERTO_LDAP_TLS:-389}:389"
      - "${PUERTO_LDAP_SSL:-686}:686"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0-amd64
    container_name: proyecto-ldap-ui
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: false
    ports:
      - "${PUERTO_LDAP_UI:-9090}:80"
    depends_on:
      - ldap

  moodle:
    container_name: proyecto-server-moodle
    build:
      context: ./moodle
      dockerfile: Dockerfile
      args:
        - MOODLE_VERSION=v4.4.8
    restart: unless-stopped
    environment:
      MOODLE_USERNAME: ${USUARIO_MOODLE:-admin_moodle}
      MOODLE_PASSWORD: ${PASS_MOODLE:-1234}
      DB_TYPE: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_PREFIX: mdl_
      SITE_URL: ${URL_IP_MOODLE:-http://10.0.2.10}
    ports:
      - 80:8080
    volumes:
      - moodle_data:/var/www/moodledata
      - moodle_html:/var/www/html
    depends_on:
      - postgres

  dns:
    image: ubuntu/bind9:9.18-24.04_edge
    container_name: proyecto-server-dns
    environment:
      - BIND9_USER=root
      - TZ=Europe/Madrid
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "953:953/tcp"
    volumes:
      - ./server-dns/config:/etc/bind
    restart: unless-stopped
    
  dhcp:
    image: networkboot/dhcpd:1.3.0
    container_name: proyecto-server-dhcp
    network_mode: "host"
    volumes:
      - ./server-dhcp/dhcpd.conf:/data/dhcpd.conf
    restart: unless-stopped

volumes:
  postgres_data:
  ldap_data:
  ldap_config:
  moodle_data:
  moodle_html: